FROM node:20-alpine AS builder
ENV NODE_ENV production

WORKDIR /app

COPY package*.json .
RUN npm i

COPY .env.template .env

COPY . .

RUN npm run build


FROM nginx:1.27.2-alpine AS production
ENV NODE_ENV production

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
