name: Frontend CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/
    permissions:
      contents: read
      packages: write
    env:
      GHCR_IMAGE_NAME: stp-babushka-frontend
      GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/stp-babushka-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: frontend/
          file: frontend/Dockerfile.prod
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}:${{ github.sha }}
            ${{ env.GHCR_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Delete old versions of package
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.GHCR_IMAGE_NAME }}
          package-type: container
          min-versions-to-keep: 3
