-- Inserting Data


INSERT INTO JOBPOSITION (TITLE) VALUES ('Manager');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Engineer');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Technician');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Operator');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Supervisor');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Quality Control');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Maintenance');
INSERT INTO JOBPOSITION (TITLE) VALUES ('HR');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Finance');
INSERT INTO JOBPOSITION (TITLE) VALUES ('Sales');


INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER, JOB_POSITION_ID) VALUES ('Ivan', 'Ivanov', 'Ivanovich', 'M', 1);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER, JOB_POSITION_ID) VALUES ('Jane', 'Smith', 'Elizabeth', 'F', 2);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER, JOB_POSITION_ID) VALUES ('Robert', 'Johnson', 'James', 'M', 2);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER, JOB_POSITION_ID) VALUES ('Michael', 'Williams', 'Andrew', 'M', 3);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, MIDDLE_NAME, GENDER, JOB_POSITION_ID) VALUES ('Sarah', 'Jones', 'Marie', 'F', 4);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, JOB_POSITION_ID) VALUES ('John', 'Doe', 'M', 5);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, JOB_POSITION_ID) VALUES ('Jessica', 'Brown', 'F', 6);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, JOB_POSITION_ID) VALUES ('Thomas', 'Davis', 'M', 7);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, JOB_POSITION_ID) VALUES ('Emily', 'Miller', 'F', 2);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, JOB_POSITION_ID) VALUES ('Daniel', 'Wilson', 'M', 2);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, JOB_POSITION_ID) VALUES ('Nancy', 'Moore', 'F', 2);


INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Wooden handle for tool', 8);
-- Деревянная рукоятка для инструмента
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Metal blank for spanner', 9);
-- Металлическая заготовка для гаечного ключа
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Plastic housing for power tool', 11);
-- Пластиковый корпус для электроинструмента
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Metal fastening for cabinet', 6);
-- Металлическое крепление для шкафа
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Plastic fastening for cables', 14);
-- Пластиковое крепление для кабелей
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Wooden stand for tool', 9);
-- Деревянная подставка для инструмента
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Rubber seal', 10);
-- Резиновое уплотнение
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Metal protective grille for ventilation', 13);
-- Металлическая защитная решетка для вентиляции
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Plastic handle for garden tool', 9);
-- Пластиковая рукоятка для садового инструмента
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Plastic panel for electrical switchboard', 16);
-- Пластиковая панель для электрической щитовой
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Metal support for rack', 19);
-- Металлическая опора для стойки
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Plastic cover for lamp', 8);
-- Пластиковый кожух для лампы
INSERT INTO PRODUCT (TITLE, AVERAGE_PRODUCTION_TIME) VALUES ('Metal clamp for pipe', 4);
-- Металлический зажим для трубы


INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Vertical milling machine');
-- Вертикально-фрезерный станок
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Welding machine');
-- Сварочный аппарат
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Measuring instrument');
-- Измерительный прибор
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Power tool');
-- Электроинструмент
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Lathe');
-- Токарный станок
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Horizontal milling machine');
-- Горизонтально-фрезерный станок
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Bench-top milling machine');
-- Станок фрезерный настольный
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Drilling and milling machine');
-- Станок сверлильно-фрезерный
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Forging and pressing machine');
-- Станок ковочно-прессовый
INSERT INTO EQUIPMENTTYPE (TITLE) VALUES ('Molding press');
-- Пресс литьевой


INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Gigant WLT-460', 1, TO_DATE('2022-01-01', 'YYYY-MM-DD'), 1);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('BELMASH WL-300/450 S078A', 2, TO_DATE('2022-02-01', 'YYYY-MM-DD'), 2);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Stalex XW5032B DRO', 3, TO_DATE('2022-03-01', 'YYYY-MM-DD'), 3);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Optimum МТ200', 4, TO_DATE('2022-04-01', 'YYYY-MM-DD'), 4);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Optimum UF200', 5, TO_DATE('2022-05-01', 'YYYY-MM-DD'), 5);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Optimum MB4P', 6, TO_DATE('2022-06-01', 'YYYY-MM-DD'), 6);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('ArtTech XL8145', 7, TO_DATE('2022-07-01', 'YYYY-MM-DD'), 7);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('EUROMET FW30', 8, TO_DATE('2022-08-01', 'YYYY-MM-DD'), 8);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Eurometal PH-25T', 9, TO_DATE('2022-09-01', 'YYYY-MM-DD'), 9);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, RESPONSIBLE_EMPLOYEE_ID) VALUES ('PDM 3000 Cansa', 10, TO_DATE('2022-10-01', 'YYYY-MM-DD'), 10);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Gigant WML MMA-160', 1, TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2022-01-10', 'YYYY-MM-DD'), 1);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('DYP-S-2RT', 2, TO_DATE('2022-02-01', 'YYYY-MM-DD'), TO_DATE('2022-02-10', 'YYYY-MM-DD'), 2);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Resanta SAI 250 65/6', 3, TO_DATE('2022-03-01', 'YYYY-MM-DD'), TO_DATE('2022-03-10', 'YYYY-MM-DD'), 3);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Equipment14', 4, TO_DATE('2022-04-01', 'YYYY-MM-DD'), TO_DATE('2022-04-10', 'YYYY-MM-DD'), 4);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Equipment15', 5, TO_DATE('2022-05-01', 'YYYY-MM-DD'), TO_DATE('2022-05-10', 'YYYY-MM-DD'), 5);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Equipment16', 6, TO_DATE('2022-06-01', 'YYYY-MM-DD'), TO_DATE('2022-06-10', 'YYYY-MM-DD'), 6);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Equipment17', 7, TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2022-07-10', 'YYYY-MM-DD'), 7);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Equipment18', 8, TO_DATE('2022-08-01', 'YYYY-MM-DD'), TO_DATE('2022-08-10', 'YYYY-MM-DD'), 8);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Equipment19', 9, TO_DATE('2022-09-01', 'YYYY-MM-DD'), TO_DATE('2022-09-10', 'YYYY-MM-DD'), 9);
INSERT INTO EQUIPMENT (TITLE, TYPE_ID, DATE_OF_COMMISSIONING, DATE_OF_LAST_SERVICE, RESPONSIBLE_EMPLOYEE_ID) VALUES ('Equipment20', 10, TO_DATE('2022-10-01', 'YYYY-MM-DD'), TO_DATE('2022-10-10', 'YYYY-MM-DD'), 10);


INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Hammer', 100, 789);
-- Молоток
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Saw', 99, 547);
-- Пила
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Cutter', 86, 432);
-- Резец
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Hacksaw', 79, 356);
-- Пила по металлу
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Micrometer', 142, 683);
-- Микрометр
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Jigsaw', 351, 784);
-- Лобзик
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Tweezers', 135, 356);
-- Пинцет
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Soldering iron', 478, 742);
-- Паяльник
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Rasp', 572, 268);
-- Наждачная бумага
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Grinding machine', 54, 235);
-- Шлифовальный станок
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Glue gun', 354, 235);
-- Пистолет для клея
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Lathe knife', 513, 235);
-- Нож токарный
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Grinding machine', 521, 235);
-- Шлифовальный станок
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Calibre', 125, 235);
-- Калибр
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Cutter', 789, 235);
-- Резец
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Ruler', 679, 235);
-- Линейка
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Knife', 865, 235);
-- Нож
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Mold', 431, 235);
-- Форма
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Guillotine knife', 246, 235);
-- Нож гильотины
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Electric drill', 321, 235);
-- Электродрель
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Screwdriver', 541, 235);
-- Отвертка
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Sandpaper', 563, 235);
-- Наждачная бумага
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Laser cutter', 145, 235);
-- Лазерный резак
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Bent knife', 567, 235);
-- Гнутый нож
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Electric knife', 132, 235);
-- Электронож
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Plastic milling cutter', 342, 235);
-- Пластиковый фрезер
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Welding heat gun', 441, 235);
-- Паяльная термопушка
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Band saw', 561, 235);
-- Ленточная пила
INSERT INTO TOOLS (TITLE, TOTAL_AMOUNT, WEAR_DEGREE) VALUES ('Drill', 531, 235);
-- Дрель


INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('AA-001-01', 1, 1);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('AA-001-01', 1, 11);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('BB-002-02', 2, 2);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('BB-002-02', 2, 12);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('CC-003-03', 3, 3);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('CC-003-03', 3, 13);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('DD-004-04', 4, 4);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('DD-004-04', 4, 14);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('EE-005-05', 5, 5);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('EE-005-05', 5, 15);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('FF-006-06', 6, 6);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('FF-006-06', 6, 16);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('GG-007-07', 7, 7);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('GG-007-07', 7, 17);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('HH-008-08', 8, 8);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('HH-008-08', 8, 18);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('II-009-09', 9, 9);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('II-009-09', 9, 19);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('JJ-010-10', 10, 10);
INSERT INTO TECHNOLOGICALMAP (MAP_NUMBER, PRODUCT_ID, EQUIPMENT_ID) VALUES ('JJ-010-10', 10, 20);


INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (1, 1, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (1, 2, 4);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (1, 3, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (1, 4, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (2, 2, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (2, 3, 4);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (2, 4, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (3, 3, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (3, 4, 1);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (4, 4, 4);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (4, 5, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (4, 6, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (5, 5, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (5, 6, 8);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (5, 7, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (6, 6, 1);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (6, 7, 7);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (7, 7, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (7, 8, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (8, 8, 4);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (8, 9, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (9, 9, 7);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (9, 10, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (10, 10, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (10, 10, 8);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (10, 11, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (10, 12, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (11, 13, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (11, 14, 4);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (11, 15, 6);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (12, 16, 1);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (12, 17, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (13, 18, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (13, 19, 7);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (14, 20, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (14, 21, 4);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (15, 22, 6);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (15, 23, 1);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (16, 24, 3);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (16, 25, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (17, 26, 7);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (17, 27, 2);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (18, 28, 4);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (18, 22, 6);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (19, 23, 5);
INSERT INTO TECHNOLOGICALMAPSTOOLS (TECHNOLOGICAL_MAP_ID, TOOLS_ID, NUMBER_OF_REQUIRED_TOOLS) VALUES (20, 21, 3);


INSERT ALL
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (1, TO_DATE('2023-01-12', 'YYYY-MM-DD'), TO_DATE('2023-01-14', 'YYYY-MM-DD'), 11, 5)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (1, TO_DATE('2023-01-12', 'YYYY-MM-DD'), TO_DATE('2023-01-13', 'YYYY-MM-DD'), 5, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (1, TO_DATE('2023-02-22', 'YYYY-MM-DD'), TO_DATE('2023-02-25', 'YYYY-MM-DD'), 2, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-01-02', 'YYYY-MM-DD'), 13, 4)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (1, TO_DATE('2024-01-02', 'YYYY-MM-DD'), TO_DATE('2024-01-03', 'YYYY-MM-DD'), 20, 3)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (1, TO_DATE('2024-01-03', 'YYYY-MM-DD'), TO_DATE('2024-01-04', 'YYYY-MM-DD'), 10, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (2, TO_DATE('2024-02-04', 'YYYY-MM-DD'), TO_DATE('2024-02-06', 'YYYY-MM-DD'), 20, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (2, TO_DATE('2024-06-13', 'YYYY-MM-DD'), TO_DATE('2024-06-25', 'YYYY-MM-DD'), 11, 2)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (2, TO_DATE('2024-02-14', 'YYYY-MM-DD'), TO_DATE('2024-02-16', 'YYYY-MM-DD'), 25, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (3, TO_DATE('2024-03-04', 'YYYY-MM-DD'), TO_DATE('2024-03-07', 'YYYY-MM-DD'), 31, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (3, TO_DATE('2024-09-11', 'YYYY-MM-DD'), TO_DATE('2024-09-12', 'YYYY-MM-DD'), 11, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (3, TO_DATE('2023-12-30', 'YYYY-MM-DD'), TO_DATE('2024-01-05', 'YYYY-MM-DD'), 47, 4)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (4, TO_DATE('2023-11-05', 'YYYY-MM-DD'), TO_DATE('2023-11-07', 'YYYY-MM-DD'), 11, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (4, TO_DATE('2024-04-05', 'YYYY-MM-DD'), TO_DATE('2024-04-07', 'YYYY-MM-DD'), 45, 2)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (5, TO_DATE('2024-05-06', 'YYYY-MM-DD'), TO_DATE('2024-05-08', 'YYYY-MM-DD'), 51, 2)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (6, TO_DATE('2024-06-07', 'YYYY-MM-DD'), TO_DATE('2024-06-09', 'YYYY-MM-DD'), 66, 3)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (7, TO_DATE('2024-07-08', 'YYYY-MM-DD'), TO_DATE('2024-07-12', 'YYYY-MM-DD'), 70, 3)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (8, TO_DATE('2024-08-09', 'YYYY-MM-DD'), TO_DATE('2024-08-15', 'YYYY-MM-DD'), 87, 4)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (9, TO_DATE('2024-09-10', 'YYYY-MM-DD'), TO_DATE('2024-09-17', 'YYYY-MM-DD'), 9, 0)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (10, TO_DATE('2024-10-11', 'YYYY-MM-DD'), TO_DATE('2024-10-22', 'YYYY-MM-DD'), 18, 5)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (10, TO_DATE('2023-01-15', 'YYYY-MM-DD'), TO_DATE('2023-01-20', 'YYYY-MM-DD'), 15, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (10, TO_DATE('2023-02-10', 'YYYY-MM-DD'), TO_DATE('2023-02-15', 'YYYY-MM-DD'), 20, 2)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (10, TO_DATE('2023-03-05', 'YYYY-MM-DD'), TO_DATE('2023-03-10', 'YYYY-MM-DD'), 25, 2)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (10, TO_DATE('2023-04-01', 'YYYY-MM-DD'), TO_DATE('2023-04-05', 'YYYY-MM-DD'), 30, 3)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (10, TO_DATE('2023-05-10', 'YYYY-MM-DD'), TO_DATE('2023-05-15', 'YYYY-MM-DD'), 35, 3)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (10, TO_DATE('2023-06-20', 'YYYY-MM-DD'), TO_DATE('2023-06-25', 'YYYY-MM-DD'), 40, 4)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (11, TO_DATE('2023-07-15', 'YYYY-MM-DD'), TO_DATE('2023-07-20', 'YYYY-MM-DD'), 45, 4)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (11, TO_DATE('2023-08-10', 'YYYY-MM-DD'), TO_DATE('2023-08-15', 'YYYY-MM-DD'), 50, 5)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (11, TO_DATE('2023-09-05', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), 55, 5)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (11, TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2023-10-05', 'YYYY-MM-DD'), 60, 6)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (11, TO_DATE('2023-11-10', 'YYYY-MM-DD'), TO_DATE('2023-11-15', 'YYYY-MM-DD'), 65, 6)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (11, TO_DATE('2023-12-20', 'YYYY-MM-DD'), TO_DATE('2023-12-25', 'YYYY-MM-DD'), 70, 7)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (12, TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2024-01-20', 'YYYY-MM-DD'), 75, 7)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (12, TO_DATE('2024-02-10', 'YYYY-MM-DD'), TO_DATE('2024-02-15', 'YYYY-MM-DD'), 80, 8)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (13, TO_DATE('2024-03-05', 'YYYY-MM-DD'), TO_DATE('2024-03-10', 'YYYY-MM-DD'), 85, 8)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (13, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-04-05', 'YYYY-MM-DD'), 90, 9)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (13, TO_DATE('2024-05-10', 'YYYY-MM-DD'), TO_DATE('2024-05-15', 'YYYY-MM-DD'), 95, 9)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (14, TO_DATE('2024-06-20', 'YYYY-MM-DD'), TO_DATE('2024-06-25', 'YYYY-MM-DD'), 135, 17)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (14, TO_DATE('2024-06-21', 'YYYY-MM-DD'), TO_DATE('2024-06-25', 'YYYY-MM-DD'), 97, 7)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (15, TO_DATE('2024-06-22', 'YYYY-MM-DD'), TO_DATE('2024-06-25', 'YYYY-MM-DD'), 74, 8)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (15, TO_DATE('2024-06-23', 'YYYY-MM-DD'), TO_DATE('2024-06-25', 'YYYY-MM-DD'), 27, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (16, TO_DATE('2024-06-24', 'YYYY-MM-DD'), TO_DATE('2024-06-25', 'YYYY-MM-DD'), 16, 0)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (16, TO_DATE('2024-06-25', 'YYYY-MM-DD'), TO_DATE('2024-06-27', 'YYYY-MM-DD'), 387, 46)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (17, TO_DATE('2024-06-26', 'YYYY-MM-DD'), TO_DATE('2024-06-28', 'YYYY-MM-DD'), 63, 12)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (17, TO_DATE('2024-06-27', 'YYYY-MM-DD'), TO_DATE('2024-06-29', 'YYYY-MM-DD'), 57, 6)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (18, TO_DATE('2024-06-28', 'YYYY-MM-DD'), TO_DATE('2024-06-29', 'YYYY-MM-DD'), 13, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (19, TO_DATE('2024-06-29', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), 75, 1)
    INTO PRODUCTION (TECHNOLOGICAL_MAP_ID, START_DATE, END_DATE, NUMBER_OF_REQUIRED_PRODUCTS, NUMBER_OF_DEFECTS) VALUES (20, TO_DATE('2024-07-20', 'YYYY-MM-DD'), TO_DATE('2024-07-25', 'YYYY-MM-DD'), 38, 1)
    -- Keep record with map_id = 20 only one!
SELECT * FROM DUAL;
