-- 1. Mutable view: Long-production products

CREATE OR REPLACE VIEW VIEW_LONG_PRODUCTION_PRODUCTS AS
SELECT
    ID,
    TITLE,
    AVERAGE_PRODUCTION_TIME
FROM PRODUCT
WHERE AVERAGE_PRODUCTION_TIME > 10
WITH CHECK OPTION;


-- Select all the data
SELECT * FROM VIEW_LONG_PRODUCTION_PRODUCTS;


-- Drop the view
-- DROP VIEW VIEW_LONG_PRODUCTION_PRODUCTS;
