-- 3. Immutable view: Male employees


CREATE OR REPLACE VIEW VIEW_MALE_EMPLOYEES AS
SELECT
    E.ID AS EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.GENDER,
    JP.TITLE AS JOB_POSITION
FROM EMPLOYEE E
LEFT JOIN JOBPOSITION JP ON E.JOB_POSITION_ID = JP.ID
WHERE E.GENDER = 'M'
ORDER BY E.ID;


-- Select all the data
SELECT * FROM VIEW_MALE_EMPLOYEES;


-- Drop the view
-- DROP VIEW VIEW_MALE_EMPLOYEES;
