-- 5. View accessible only during working hours


CREATE OR REPLACE VIEW VIEW_EMPLOYEE_WORK_HOURS AS
SELECT
    TM.MAP_NUMBER,
    PR.TITLE,
    P.START_DATE,
    P.END_DATE,
    P.NUMBER_OF_REQUIRED_PRODUCTS,
    P.NUMBER_OF_DEFECTS
FROM PRODUCTION P
LEFT JOIN TECHNOLOGICALMAP TM ON P.TECHNOLOGICAL_MAP_ID = TM.ID
LEFT JOIN PRODUCT PR ON TM.PRODUCT_ID = PR.ID
WHERE
    TO_CHAR(SYSTIMESTAMP AT TIME ZONE 'Europe/Moscow', 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT', 'SUN')
    AND
    TO_CHAR(SYSTIMESTAMP AT TIME ZONE 'Europe/Moscow', 'HH24:MI') BETWEEN '09:00' AND '16:00';


-- Select all the data
SELECT * FROM VIEW_EMPLOYEE_WORK_HOURS;


-- Drop the view
-- DROP VIEW VIEW_EMPLOYEE_WORK_HOURS;
