# Generated by Django 5.0.1 on 2024-11-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersessions',
            options={'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
    ]
